"""Initial supermarket schema. Alembic is the sole schema authority."""

from alembic import op

revision = "0001_foundation"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
    CREATE TABLE categories (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      parent_id BIGINT REFERENCES categories(id) ON DELETE RESTRICT,
      name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      CHECK (parent_id IS NULL OR parent_id <> id)
    )
    """)
    op.execute("CREATE INDEX ix_categories_parent_id ON categories(parent_id)")
    op.execute("""
    CREATE TABLE products (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
      name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE,
      description TEXT NOT NULL DEFAULT '', sku TEXT NOT NULL UNIQUE,
      price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
      old_price NUMERIC(12,2) CHECK (old_price >= 0), unit TEXT NOT NULL,
      image_url TEXT NOT NULL DEFAULT '',
      stock_quantity NUMERIC(12,3) NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
    """)
    op.execute("CREATE INDEX ix_products_category_id ON products(category_id)")
    op.execute("""
    CREATE FUNCTION set_updated_at() RETURNS TRIGGER LANGUAGE plpgsql AS $$
    BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
    $$
    """)
    op.execute("""
    CREATE TRIGGER products_updated_at BEFORE UPDATE ON products
      FOR EACH ROW EXECUTE FUNCTION set_updated_at()
    """)
    op.execute("""
    CREATE TABLE orders (
      id UUID PRIMARY KEY, customer_name TEXT NOT NULL, phone TEXT NOT NULL, address TEXT NOT NULL,
      latitude DOUBLE PRECISION CHECK (latitude BETWEEN -90 AND 90),
      longitude DOUBLE PRECISION CHECK (longitude BETWEEN -180 AND 180),
      subtotal NUMERIC(12,2) NOT NULL CHECK (subtotal >= 0),
      delivery_price NUMERIC(12,2) NOT NULL CHECK (delivery_price >= 0),
      total NUMERIC(12,2) NOT NULL CHECK (total >= 0 AND total = subtotal + delivery_price),
      distance_meters INTEGER CHECK (distance_meters >= 0),
      delivery_duration_seconds INTEGER CHECK (delivery_duration_seconds >= 0),
      status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending','confirmed','delivering','completed','cancelled')),
      comment TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      CHECK ((latitude IS NULL) = (longitude IS NULL))
    )
    """)
    op.execute("""
    CREATE TABLE order_items (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
      product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
      product_name TEXT NOT NULL, quantity NUMERIC(12,3) NOT NULL CHECK (quantity > 0),
      unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
      total_price NUMERIC(12,2) NOT NULL
        CHECK (total_price >= 0 AND total_price = ROUND(quantity * unit_price, 2))
    )
    """)
    op.execute("CREATE INDEX ix_order_items_order_id ON order_items(order_id)")
    op.execute("CREATE INDEX ix_order_items_product_id ON order_items(product_id)")


def downgrade():
    op.drop_table("order_items")
    op.drop_table("orders")
    op.drop_table("products")
    op.execute("DROP FUNCTION set_updated_at()")
    op.drop_table("categories")
